import { Inter } from "next/font/google";
import "./globals.css";
import SessionWrapper from "./component/SessionWrapper";
import Header from "./component/Header";
import { Toaster } from "sonner";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <SessionWrapper>
        <Header/>
        <div>
        {children}
        <Toaster/>   
        </div>
      </SessionWrapper>
        </body>
    </html>
  );
}
